version: '3'
services:
  ricette:
    container_name: ricette
    image: ricette
    build:
      dockerfile: ricette.df
      context: ./ricette
    depends_on:
      - ricetteDB
      - consul
      - zookeeper
      - kafka
  ricetteDB:
    image: postgres
    container_name: ricetteDB
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ricette
    volumes:
      - "./ricetteDB:/var/lib/postgresql/data"
  connessioni:
    container_name: connessioni
    image: connessioni
    build:
      dockerfile: connessioni.df
      context: ./connessioni
    depends_on:
      - connessioniDB
      - consul
      - kafka
      - zookeeper
  connessioniDB:
    image: postgres
    container_name: connessioniDB
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=connessioni
    volumes:
      - "./connessioniDB:/var/lib/postgresql/data"
  apigateway:
    container_name: apigateway
    image: apigateway
    build:
      dockerfile: api-gateway.df
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - consul
  ricette-seguite:
    container_name: ricette-seguite
    image: ricette-seguite
    build:
      dockerfile: ricette-seguite.df
      context: ./ricette-seguite
    depends_on:
      - consul
      - ricette
      - connessioni
      - kafka
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ricette-service-event-channel:4:1,connessioni-service-event-channel:4:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  consul:
    image: consul
    ports:
      - "8500:8500"
    container_name: consul
 
